drop table if exists accounts;

create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    primary key(id)
);

insert into accounts(name,balance)
values('Bob',10000);

insert into accounts(name,balance)
values('Alice',10000);

SELECT * FROM accounts;

-- create stored procedures
CREATE OR REPLACE PROCEDURE pr_transfer_amount(sender_id INTEGER, receiver_id INTEGER, amount NUMERIC)
AS 
$$
	BEGIN

		UPDATE accounts
		SET balance = balance - amount
		WHERE id = sender_id;
	
		UPDATE accounts
		SET balance = balance + amount
		WHERE id = receiver_id;
	
		COMMIT;

	END;

$$ LANGUAGE PLPGSQL;

CALL pr_transfer_amount(1, 2, 100);

SELECT * FROM accounts;

-- return value
CREATE OR REPLACE PROCEDURE pr_return_value(INOUT rec record DEFAULT NULL)
AS 
$$

	BEGIN

		SELECT * from accounts INTO rec;

	END;

$$ LANGUAGE PLPGSQL;

CALL pr_return_value();
